### ISSUE TITLE
Issue running example-helloworld

### ISSUE THREAD

**Issue by ghost** [codius/codius-cli#4]
I have installed the CLI as per the instructions (sudo npm install -g codius) and cloned the example-helloworld into a new directory. I'm running this on Ubuntu Trusty 14.04 (AWS), node version v0.10.33.

When I execute 'codius run' I am getting an error - trace below:

info:    Running contract 7f445e537b535225bf8da43a8ad3d1670a93009069d5e29cf2d65236ef28dfb1
warn:    No secret provided! Generating a random secret, please do not do this in production.
Possibly unhandled TypeError: Object.keys called on non-object
    at Function.keys (native)
    at Sandbox._spawnChildToRunCode (/usr/lib/node_modules/codius/node_modules/codius-engine/node_modules/codius-node-sandbox/sandbox.js:127:10)
    at Sandbox.run (/usr/lib/node_modules/codius/node_modules/codius-engine/node_modules/codius-node-sandbox/sandbox.js:87:35)
    at ContractRunner.run (/usr/lib/node_modules/codius/node_modules/codius-engine/lib/contractrunner.js:116:17)
    at Engine.runContract (/usr/lib/node_modules/codius/node_modules/codius-engine/lib/engine.js:106:10)
    at runContract (/usr/lib/node_modules/codius/lib/commands/run.js:60:14)
    at /usr/lib/node_modules/codius/lib/commands/run.js:56:7
    at tryCatch1 (/usr/lib/node_modules/codius/node_modules/bluebird/js/main/util.js:45:21)
    at Promise$_callHandler [as _callHandler](/usr/lib/node_modules/codius/node_modules/bluebird/js/main/promise.js:660:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler](/usr/lib/node_modules/codius/node_modules/bluebird/js/main/promise.js:675:18)

Any help appreciated!

**Comment by emschwartz** [comment]
Is this still an issue?
