### ISSUE TITLE
Issue with selftest

### ISSUE THREAD

**Issue by lukeburns** [codius/codius-cli#7]
I'm having trouble with `codius selftest`.

```
codius selftest
info:    Running self-test. If it works, it should print "Self-test succeeded"
warn:    No secret provided! Generating a random secret, please do not do this in production.
Possibly unhandled ReferenceError: manifest_hash is not defined
    at Engine._loadManifest (/usr/lib/node_modules/codius/node_modules/codius-engine/lib/engine.js:148:91)
    at Engine.runContract (/usr/lib/node_modules/codius/node_modules/codius-engine/lib/engine.js:98:23)
    at runContract (/usr/lib/node_modules/codius/lib/commands/selftest.js:61:14)
    at /usr/lib/node_modules/codius/lib/commands/selftest.js:57:7
    at tryCatch1 (/usr/lib/node_modules/codius/node_modules/bluebird/js/main/util.js:45:21)
    at Promise._callHandler (/usr/lib/node_modules/codius/node_modules/bluebird/js/main/promise.js:571:13)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/codius/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAt (/usr/lib/node_modules/codius/node_modules/bluebird/js/main/promise.js:713:18)
    at Promise._settlePromises (/usr/lib/node_modules/codius/node_modules/bluebird/js/main/promise.js:854:14)
    at Async._consumeFunctionBuffer (/usr/lib/node_modules/codius/node_modules/bluebird/js/main/async.js:85:12)
```

I get the same error running the helloworld example.

**Comment by eliotweber** [comment]
See codius-engine Pull Request #30 for a fix:  https://github.com/codius/codius-engine/pull/30

**Comment by justmoon** [comment]
Thanks for the report. PR is now merged upstream. Give it another try please!

**Comment by step21** [comment]
Seems to work now. Though what is the recommended way to pull changes? Github? Npm didn't have the update yet.

**Comment by stevenzeiler** [comment]
Github is the recommended way to pull changes between tagged releases, which will then be uploaded to NPM.

**Comment by step21** [comment]
Ok, thanks!
